version: 2.2.0.{build}

# environment variables
environment:
  COVERALLS_REPO_TOKEN:
    secure: IH0irnGyWP3Z9jcxBz6LsnYIH2pStkwq23/tMRWFCFswYfTA5DvVPTp4pbz9r0Hi
  NUGET_API_KEY:
    secure: FLH3rCl/Okbe8lchEljJpnCPrs18DiTlm5oQn3i03yAEIjNhpQcWQDFV3VMPXthc

# Build with Visual Studio 2017
image: Visual Studio 2017

# Build Release and Coverage (2 build jobs)
configuration:
- Release
- Coverage

# fail fast (No need to build Failing Release & Coverage builds)
matrix:
  fast_finish: true

# Assembly patching, only the top level Directory.Build.props file must be patched
dotnet_csproj:
  patch: true
  file: '*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'


# restore NuGet packages
before_build:
- ps: msbuild /t:restore openkit-dotnet.sln

# build
build:
  project: openkit-dotnet.sln
  verbosity: minimal
  
# run tests with code coverage only for Coverage configuration
for:
-
  matrix:
    only:
      - configuration: Coverage
  test_script:
  - ps: |
        .\callTest.ps1 -option Coverage
  after_test: 
  - ps: |
      if ("$Env:APPVEYOR_PULL_REQUEST_NUMBER" -eq "" -And "$Env:APPVEYOR_REPO_NAME" -eq "Dynatrace/openkit-dotnet")
      {
          $coveralls = "$env:USERPROFILE\.nuget\packages\coveralls.io\1.4.2\tools\coveralls.net.exe"
          & $coveralls --opencover .\coverage.xml -r $Env:COVERALLS_REPO_TOKEN
      }
      else
      {
          Write-Host("Skipping coveralls.io upload")
          Write-Host("APPVEYOR_PULL_REQUEST_NUMBER=$Env:APPVEYOR_PULL_REQUEST_NUMBER")
          Write-Host("APPVEYOR_REPO_NAME=$Env:APPVEYOR_REPO_NAME")
      }
-
  matrix:
    only:
      - configuration: Release
  test_script:
  - ps: |
        .\callTest.ps1 -option Release
